build.gradle
src/main/java/com/softeer/podo/common/entity/DateEntity.java
src/main/java/com/softeer/podo/common/response/CommonResponse.java
src/main/java/com/softeer/podo/common/response/ErrorCode.java
src/main/java/com/softeer/podo/config/FilterConfig.java
src/main/java/com/softeer/podo/config/WebConfig.java
src/main/java/com/softeer/podo/security/Auth.java
src/main/java/com/softeer/podo/security/AuthArgumentResolver.java
src/main/java/com/softeer/podo/security/AuthInfo.java
src/main/java/com/softeer/podo/security/jwt/ExceptionHandleFilter.java
src/main/java/com/softeer/podo/security/jwt/JwtAuthenticationFilter.java
src/main/java/com/softeer/podo/security/jwt/TokenInfo.java
src/main/java/com/softeer/podo/security/jwt/TokenProvider.java
src/main/java/com/softeer/podo/security/jwt/exception/EmptyTokenException.java
src/main/java/com/softeer/podo/security/jwt/exception/InvalidTokenException.java
src/main/java/com/softeer/podo/test/controller/TestController.java
src/main/java/com/softeer/podo/test/exception/TestExceptionHandler.java
src/main/java/com/softeer/podo/test/model/dto/TestSignUpRequestDto.java
src/main/java/com/softeer/podo/test/model/dto/TestSignUpResponseDto.java
src/main/java/com/softeer/podo/test/repository/TestRepository.java
src/main/java/com/softeer/podo/test/service/TestService.java
src/main/java/com/softeer/podo/user/model/entity/Role.java
src/main/java/com/softeer/podo/user/model/entity/TestUser.java
src/main/resources/application.properties
src/main/resources/application.yml
src/test/java/com/softeer/podo/common/SecretKeyGenerateTest.java

Issue #7 
- 테스트용 컨트롤러인 TestController(/test/**)를 추가했습니다.
- 성공 여부, code, message, 응답정보를 담는 응답 프레임을 만들었습니다.
- jwt 기반으로 토큰 생성(서명)하고, nimbus-jose-jwt lib을 이용한 토큰 암호화를 진행했습니다.
- 리졸버를 사용하여 어노테이션 기반으로 인증정보가 동적으로 파라미터 바인딩되도록 했습니다.
- 시큐리티 없이 인증인가 필터 추가해본 경험은 처음이라, 추후에라도 side effect 발생시 저한테 얘기해주시면 됩니다!

[Feature] 인증 필터 추가

---

build.gradle
src/main/java/com/softeer/podo/PodoApplication.java
src/main/java/com/softeer/podo/common/response/ErrorCode.java
src/main/java/com/softeer/podo/common/utils/NumberUtils.java
src/main/java/com/softeer/podo/config/RedisConfig.java
src/main/java/com/softeer/podo/verification/controller/VerificationController.java
src/main/java/com/softeer/podo/verification/exception/VerificationExceptionHandler.java
src/main/java/com/softeer/podo/verification/facade/VerificationFacade.java
src/main/java/com/softeer/podo/verification/service/MessageService.java
src/main/java/com/softeer/podo/verification/service/RedisService.java
src/main/java/com/softeer/podo/verification/service/VerificationService.java
src/main/resources/application.yml

Issue #13 
- 로컬에 Redis 설치
- 인증 요청시 Redis에 인증번호 저장 후 메시지 발송
- 인증번호 검증시 Redis에서 인증번호를 찾고 일치여부 확인 후 토큰 발급
- 인증번호 저장시 중복로직 검사해야 합니다. 승구님 작업 끝나시면 RDB 대조하여 전화번호 중복 검사할 예정입니다.

[Feature] 인증 로직 Redis 연동

---

.github/workflows/build.yml
src/main/java/com/softeer/podo/security/jwt/TokenProvider.java

[Chore] Actions CI Test

---

.github/workflows/deploy.yml
appspec.yml
script/start.sh
script/stop.sh

[Chore] Actions CD Test

---

.github/workflows/deploy.yml

[Chore] OIDC 인증을 위한 id-token 권한 허용

---

build.gradle

[Chore] plain.jar 생성 방지

---

src/main/java/com/softeer/podo/common/response/ErrorCode.java
src/main/java/com/softeer/podo/config/SwaggerConfig.java
src/main/java/com/softeer/podo/event/service/EventLotsService.java
src/main/java/com/softeer/podo/security/Auth.java
src/main/java/com/softeer/podo/security/jwt/TokenProvider.java
src/main/java/com/softeer/podo/user/model/dto/UserDto.java
src/main/java/com/softeer/podo/user/repository/UserRepository.java
src/main/java/com/softeer/podo/user/service/UserService.java
src/main/java/com/softeer/podo/verification/controller/VerificationController.java
src/main/java/com/softeer/podo/verification/exception/DuplicatePhoneNumException.java
src/main/java/com/softeer/podo/verification/exception/VerificationExceptionHandler.java
src/main/java/com/softeer/podo/verification/facade/VerificationFacade.java

[Feature] 인증 로직 마무리, Swagger 추가

---

src/main/java/com/softeer/podo/config/FilterConfig.java
src/test/java/com/softeer/podo/admin/controller/AdminControllerTest.java
src/test/java/com/softeer/podo/admin/service/AdminServiceTest.java

#38 [Test] 테스트 코드 작성
Service 테스트에서는 세부 로직 테스트 구현했습니다.
Controller 테스트의 경우 mockMvc로 request테스트 진행했습니다.

[Test] admin api 테스트 코드 작성

---

build.gradle
src/main/java/com/softeer/podo/common/response/ErrorCode.java
src/main/java/com/softeer/podo/common/utils/URLUtils.java
src/main/java/com/softeer/podo/security/jwt/ExceptionHandleFilter.java
src/main/java/com/softeer/podo/security/jwt/TokenProvider.java
src/main/java/com/softeer/podo/verification/facade/VerificationFacade.java
src/main/java/com/softeer/podo/verification/service/MessageService.java
src/main/java/com/softeer/podo/verification/service/VerificationService.java
src/test/java/com/softeer/podo/common/TokenProviderBase.java
src/test/java/com/softeer/podo/common/VerificationFacadeBase.java
src/test/java/com/softeer/podo/common/VerificationServiceBase.java
src/test/java/com/softeer/podo/security/SecretKeyGenerateTest.java
src/test/java/com/softeer/podo/security/TokenProviderTest.java
src/test/java/com/softeer/podo/verification/VerificationFacadeTest.java
src/test/java/com/softeer/podo/verification/VerificationServiceTest.java
src/test/resources/application.yml

[Test] Authorization / Verification 테스트

---

build.gradle
src/main/java/com/softeer/podo/event/service/EventLotsService.java
src/test/java/com/softeer/podo/admin/controller/AdminControllerTest.java
src/test/java/com/softeer/podo/event/scheduler/CommentCheckSchedulerTest.java
src/test/java/com/softeer/podo/event/service/EventLotsServiceTest.java

[Test] 테스트 코드 작성 #38
새로운 api에 대한 테스트코드 추가
- word cloud
- CommentCheckScheduler

[Test] 랜덤 추첨 이벤트 테스트코드 추가 작성 및 테스트 코드 보완

---

src/main/java/com/softeer/podo/verification/controller/ReissueController.java
src/main/java/com/softeer/podo/verification/model/dto/response/ReissueTokenResponseDto.java
src/main/java/com/softeer/podo/verification/service/VerificationService.java
src/test/java/com/softeer/podo/common/ReissueTokenBase.java
src/test/java/com/softeer/podo/verification/ReissueTokenTest.java

[Feature] 토큰 재발급 로직 추가

---

src/main/java/com/softeer/podo/admin/controller/AdminController.java
src/main/java/com/softeer/podo/admin/service/AdminService.java
src/main/java/com/softeer/podo/event/repository/ArrivalUserRepository.java
src/main/java/com/softeer/podo/event/repository/LotsUserRepository.java

url parameter에 name이나 phoneNum parameter를 넣을 시 해당 string과 부분 일치하는 user들에 대해 paging을 적용하여 반환

[Feat] url parameter를 이용한 조건부 페이징 추가

---

src/main/java/com/softeer/podo/admin/controller/AdminController.java
src/main/java/com/softeer/podo/admin/model/dto/AdminLogDto.java
src/main/java/com/softeer/podo/admin/model/dto/response/GetAdminLogListResponseDto.java
src/main/java/com/softeer/podo/common/utils/AESUtils.java
src/main/java/com/softeer/podo/common/utils/JsonUtils.java
src/main/java/com/softeer/podo/common/utils/MdcUtils.java
src/main/java/com/softeer/podo/log/aop/AdminLogAspect.java
src/main/java/com/softeer/podo/log/filter/RequestCollectionFilter.java
src/main/java/com/softeer/podo/log/filter/RequestWrapper.java
src/main/java/com/softeer/podo/log/mapper/AdminLogMapper.java
src/main/java/com/softeer/podo/log/service/AdminLogService.java
src/main/java/com/softeer/podo/security/jwt/ExceptionHandleFilter.java
src/main/java/com/softeer/podo/security/jwt/JwtAuthenticationFilter.java
src/main/java/com/softeer/podo/security/jwt/TokenProvider.java
src/main/java/com/softeer/podo/verification/facade/VerificationFacade.java
src/main/java/com/softeer/podo/verification/service/MessageService.java
src/main/java/com/softeer/podo/verification/service/RedisService.java
src/main/java/com/softeer/podo/verification/service/VerificationService.java

Issue #21, #52, #40
- 로깅을 위해서 Mdc에 request body를 저장하고 있는데, json이 아니라 순수 string으로 받도록 수정 (json으로 받으면 json 파싱을 위한 백슬래시가 붙음)
- 단 body로 json이 아닌 객체나 바이트가 오면 문제될 수 있어보인다 -> 현재 AOP로깅 이외에 로깅을 추가할경우 메서드 수정이 필요해보임

[Feat] 어드민 로깅 조회 API 추가 및 코드 리팩토링

---

src/main/java/com/softeer/podo/admin/controller/AdminController.java
src/main/java/com/softeer/podo/admin/service/AdminService.java
src/main/java/com/softeer/podo/common/exception/CommonExceptionHandler.java
src/main/java/com/softeer/podo/event/repository/ArrivalUserRepository.java
src/main/java/com/softeer/podo/event/repository/LotsUserRepository.java
src/test/java/com/softeer/podo/admin/service/AdminServiceTest.java

createdAt 형식은 yyyy-mm-dd 로 받고, 잘못된 형식의 날짜가 오게되면 error response 발생

[Feat] userlist 반환 시 datetime 조건 추가

---

src/main/java/com/softeer/podo/event/controller/EventLotsApiController.java
src/main/java/com/softeer/podo/event/model/dto/request/LotsTypeByIdRequestDto.java
src/main/java/com/softeer/podo/event/service/EventLotsService.java

[Feature] result id를 이용하여 드라이버 유형 반환하는 api 추가

---

src/main/java/com/softeer/podo/event/model/dto/KeyWordDto.java
src/main/java/com/softeer/podo/event/model/mapper/LotsEventMapper.java

word cloud 반환시 name value로 반환되도록 수정

[Fix] word cloud 반환시 name value로 반환되도록 수정

---

src/main/java/com/softeer/podo/event/controller/EventLotsPageController.java
src/main/java/com/softeer/podo/event/model/dto/response/LotsApplicationResponseDto.java
src/main/java/com/softeer/podo/event/repository/LotsShareLinkRepository.java
src/main/java/com/softeer/podo/event/service/EventLotsService.java

[Fix] share link가 이미 응모한 사람한테도 오게끔 수정 및 공유링크 redirection 연결

---

src/main/java/com/softeer/podo/PodoApplication.java
src/main/java/com/softeer/podo/verification/controller/VerificationController.java
src/main/java/com/softeer/podo/verification/facade/VerificationFacade.java
src/main/java/com/softeer/podo/verification/service/MessageReleaseService.java
src/main/java/com/softeer/podo/verification/service/MessageService.java

[Feature] 메시지 전송방식 수정

---

src/main/java/com/softeer/podo/log/filter/RequestWrapper.java

- multipart/form-data에서 part에 Content-Type 지정하는 경우는 파일에 한정함
- 따라서 "name=file" 문자열 포함여부를 검사하여 part 데이터타입 구분

[Fix] 로깅 조건 수정

---

src/main/java/com/softeer/podo/PodoApplication.java
src/main/resources/application.yml

[Fix] CORS 에러 해결 #67
keystore 파일은 project root 폴더의 한단계 상위에 넣어두면 됩니다.

[Fix] cors 에러 해결 및 https 연결 추가

---

src/main/java/com/softeer/podo/PodoApplication.java
src/main/resources/application.yml

[Fix] CORS 에러 해결 #67
- 사설 ssl 인증서로는 브라우저단에서 막음
- cloudfront를 이용하여 https 연결을 구현했기에 https 연결 제거

[Fix] https 설정 제거

---

src/main/java/com/softeer/podo/admin/controller/AdminController.java
src/main/java/com/softeer/podo/admin/service/AdminService.java
src/main/java/com/softeer/podo/event/controller/EventLotsApiController.java
src/main/java/com/softeer/podo/event/controller/EventLotsController.java
src/main/java/com/softeer/podo/event/controller/EventLotsPageController.java
src/main/java/com/softeer/podo/event/exception/EventExceptionHandler.java
src/main/java/com/softeer/podo/event/service/EventLotsService.java
src/main/java/com/softeer/podo/log/service/AdminLogService.java
src/main/java/com/softeer/podo/verification/controller/ReissueController.java
src/main/java/com/softeer/podo/verification/controller/VerificationController.java

[Docs] swagger error code 내용 추가

---

src/main/java/com/softeer/podo/common/response/ErrorCode.java
src/main/java/com/softeer/podo/event/controller/EventLotsController.java
src/main/java/com/softeer/podo/event/exception/EventExceptionHandler.java
src/main/java/com/softeer/podo/event/exception/MaxCommentLengthException.java
src/main/java/com/softeer/podo/event/service/EventLotsService.java

[Fix] 기대평 길이 체크 및 exception 추가
